services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 9190:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/share/nginx/html
      - ./conda:/var/cache/nginx/conda
      - ./log:/var/log/nginx
    environment:
      - TZ=Asia/Shanghai
